<a href="https://colab.research.google.com/github/marsavil/Data_Science_Notebooks/blob/main/Pandas_ES_trabajando_con_diferentes_formatos_de_archivo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Aula 1 -  Leyendo Archivos CSV**

## Importando archivos csv

In [9]:
import pandas as pd
id = '1FkxSPA_xHbKlYgJhzy-C63xuZJVV2ohq'
url = f'https://drive.google.com/uc?id={id}'

df = pd.read_csv(url)
df

Id  Year_Birth   Education Marital_Status   Income  Kidhome  \
0      1826        1970  Graduation       Divorced  84835.0        0   
1         1        1961  Graduation         Single  57091.0        0   
2     10476        1958  Graduation        Married  67267.0        0   
3      1386        1967  Graduation       Together  32474.0        1   
4      5371        1989  Graduation         Single  21474.0        1   
...     ...         ...         ...            ...      ...      ...   
2235  10142        1976         PhD       Divorced  66476.0        0   
2236   5263        1977    2n Cycle        Married  31056.0        1   
2237     22        1976  Graduation       Divorced  46310.0        1   
2238    528        1978  Graduation        Married  65819.0        0   
2239   4070        1969         PhD        Married  94871.0        0   

      Teenhome Dt_Customer  Recency  MntWines  ...  MntFishProducts  \
0            0   6/16/2014        0       189  ...              111   
1            0   6/15/2014        0       464  ...                7   
2            1   5/13/2014        0       134  ...               15   
3            1   11/5/2014        0        10  ...                0   
4            0    8/4/2014        0         6  ...               11   
...        ...         ...      ...       ...  ...              ...   
2235         1    7/3/2013       99       372  ...               47   
2236         0   1/22/2013       99         5  ...                3   
2237         0   3/12/2012       99       185  ...               15   
2238         0  11/29/2012       99       267  ...              149   
2239         2    1/9/2012       99       169  ...              188   

      MntSweetProducts  MntGoldProds  NumDealsPurchases  NumWebPurchases  \
0                  189           218                  1                4   
1                    0            37                  1                7   
2                    2            30                  1                3   
3                    0             0                  1                1   
4                    0            34                  2                3   
...                ...           ...                ...              ...   
2235                48            78                  2                5   
2236                 8            16                  1                1   
2237                 5            14                  2                6   
2238               165            63                  1                5   
2239                 0           144                  1                8   

      NumCatalogPurchases  NumStorePurchases  NumWebVisitsMonth  Response  \
0                       4                  6                  1         1   
1                       3                  7                  5         1   
2                       2                  5                  2         0   
3                       0                  2                  7         0   
4                       1                  2                  7         1   
...                   ...                ...                ...       ...   
2235                    2                 11                  4         0   
2236                    0                  3                  8         0   
2237                    1                  5                  8         0   
2238                    4                 10                  3         0   
2239                    5                  4                  7         1   

      Complain  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
2235         0  
2236         0  
2237         0  
2238         0  
2239         0  

[2240 rows x 22 columns]

In [10]:
id = '1v8D2eWSfSiaCQRld90uFDKtamU_Dg1X2'
url = f'https://drive.google.com/uc?id={id}'

df_semi_colon = pd.read_csv(url, sep=';')
df_semi_colon

Id  Year_Birth   Education Marital_Status   Income  Kidhome  \
0      1826        1970  Graduation       Divorced  84835.0        0   
1         1        1961  Graduation         Single  57091.0        0   
2     10476        1958  Graduation        Married  67267.0        0   
3      1386        1967  Graduation       Together  32474.0        1   
4      5371        1989  Graduation         Single  21474.0        1   
...     ...         ...         ...            ...      ...      ...   
2235  10142        1976         PhD       Divorced  66476.0        0   
2236   5263        1977    2n Cycle        Married  31056.0        1   
2237     22        1976  Graduation       Divorced  46310.0        1   
2238    528        1978  Graduation        Married  65819.0        0   
2239   4070        1969         PhD        Married  94871.0        0   

      Teenhome Dt_Customer  Recency  MntWines  ...  MntFishProducts  \
0            0   6/16/2014        0       189  ...              111   
1            0   6/15/2014        0       464  ...                7   
2            1   5/13/2014        0       134  ...               15   
3            1   11/5/2014        0        10  ...                0   
4            0    8/4/2014        0         6  ...               11   
...        ...         ...      ...       ...  ...              ...   
2235         1    7/3/2013       99       372  ...               47   
2236         0   1/22/2013       99         5  ...                3   
2237         0   3/12/2012       99       185  ...               15   
2238         0  11/29/2012       99       267  ...              149   
2239         2    1/9/2012       99       169  ...              188   

      MntSweetProducts  MntGoldProds  NumDealsPurchases  NumWebPurchases  \
0                  189           218                  1                4   
1                    0            37                  1                7   
2                    2            30                  1                3   
3                    0             0                  1                1   
4                    0            34                  2                3   
...                ...           ...                ...              ...   
2235                48            78                  2                5   
2236                 8            16                  1                1   
2237                 5            14                  2                6   
2238               165            63                  1                5   
2239                 0           144                  1                8   

      NumCatalogPurchases  NumStorePurchases  NumWebVisitsMonth  Response  \
0                       4                  6                  1         1   
1                       3                  7                  5         1   
2                       2                  5                  2         0   
3                       0                  2                  7         0   
4                       1                  2                  7         1   
...                   ...                ...                ...       ...   
2235                    2                 11                  4         0   
2236                    0                  3                  8         0   
2237                    1                  5                  8         0   
2238                    4                 10                  3         0   
2239                    5                  4                  7         1   

      Complain  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
2235         0  
2236         0  
2237         0  
2238         0  
2239         0  

[2240 rows x 22 columns]

In [11]:
df_primeras_lineas = pd.read_csv(url, nrows=5, sep =';')
df_primeras_lineas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [12]:
df_seleccion = pd.read_csv(url, usecols = [0, 1, 4], sep=';') #se puede usar el nombre de la columna tambien
df_seleccion

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [13]:
#df_seleccion.to_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/clientes_mercado.csv')
id = '1AjNJ2GUczJPA4InSO9vsGHe-Mt6FbeIq'
url = f'https://drive.google.com/uc?id={id}'
pd.read_csv(url)

Unnamed: 0     Id  Year_Birth   Income
0              0   1826        1970  84835.0
1              1      1        1961  57091.0
2              2  10476        1958  67267.0
3              3   1386        1967  32474.0
4              4   5371        1989  21474.0
...          ...    ...         ...      ...
2235        2235  10142        1976  66476.0
2236        2236   5263        1977  31056.0
2237        2237     22        1976  46310.0
2238        2238    528        1978  65819.0
2239        2239   4070        1969  94871.0

[2240 rows x 4 columns]

El problema con este código es que crea una columna extra con los indices del data frame original

In [14]:
id = '1--jxQGtLI9uUUzQaQJjgKr3-jyQ1B0F7'
url = f'https://drive.google.com/uc?id={id}'
#df_seleccion.to_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/clientes_mercado_sin_indice.csv', index=False)
pd.read_csv(url)

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

## Ejercitación

Su desafío aquí será leer este archivo usando la función read_csv de la biblioteca Pandas. Se deben agregar algunos parámetros para que la lectura se realice correctamente. Entonces, aquí hay algunos consejos:

Asegúrese de que el archivo CSV esté separado por una coma o punto y coma.
* La codificación del archivo es ISO-8859-1.
* Las primeras tres líneas del archivo se pueden ignorar, ya que el encabezado sólo comienza en la cuarta línea.
* Las últimas 9 líneas también se pueden ignorar, ya que son sólo información sobre dónde se tomaron los datos.
* Para eliminar las últimas líneas es necesario agregar el parámetro engine='python'.

In [15]:
import chardet

In [16]:
id ='1jLVZH-zkA-bcyN37Ro9bdJA2uvSo5WG0'
url = f'https://drive.google.com/uc?id={id}'

# with open(url, 'rb') as file:
#     print(chardet.detect(file.read()))

In [17]:
df = pd.read_csv(url, encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter=9, engine='python')
df

Unidade da Federação      2008/Jan      2008/Fev      2008/Mar  \
0              Rondônia    1388528,39    2931283,42    1541682,52   
1                  Acre     902416,00    1497206,26    1794028,48   
2              Amazonas    4735529,42    7118990,57    8196635,49   
3               Roraima     657889,53     777939,31     718688,03   
4                  Pará   18864744,11   19553758,20   21937342,70   
5                 Amapá    1120973,34    1268740,33     974651,24   
6             Tocantins    3441592,69    4985688,85    6205612,60   
7              Maranhão   10723506,39   13559679,41   13985142,36   
8                 Piauí    7985142,43   10079928,25   10298372,45   
9                 Ceará   15539821,90   25735101,55   28724625,75   
10  Rio Grande do Norte    5947814,08    9509755,83   10352238,59   
11              Paraíba   10723002,45   11386274,47   12053643,87   
12           Pernambuco   14393949,89   24181400,95   29991302,71   
13              Alagoas    6243726,32    8376622,16    8408336,22   
14              Sergipe    2780750,11    3676483,16    5051473,61   
15                Bahia   21211522,47   28189304,95   34181483,52   
16         Minas Gerais   45671659,76   70194037,10   79231336,95   
17       Espírito Santo    5456723,98    9102212,86   10249595,97   
18       Rio de Janeiro   23025258,52   28394310,93   44567062,94   
19            São Paulo   91678473,48  148677526,82  156087269,23   
20               Paraná   38266347,46   55384670,52   53801318,85   
21       Santa Catarina   16504913,45   25651429,11   26743524,89   
22    Rio Grande do Sul   30931325,46   57363420,01   51547794,07   
23   Mato Grosso do Sul    5377392,11    7002472,61    8423933,19   
24          Mato Grosso    4795299,01    8684882,23    7886243,14   
25                Goiás   15310637,29   22258668,68   21442515,75   
26     Distrito Federal    4745919,19    7632480,67    9647203,26   
27                Total  408424859,23  613174269,21  664043058,38   

        2008/Abr      2008/Mai      2008/Jun      2008/Jul      2008/Ago  \
0     1525314,96    1645953,84    1406150,68    3065279,01    3231494,61   
1     1730469,42    1819443,92    1828496,00    2511754,59    2089107,14   
2     8259378,42    7831399,90    8477273,62    9368858,72    9352532,70   
3      839994,39     862347,96     832440,66     996693,09     894271,18   
4    20842829,69   23249952,88   23240687,56   24002223,56   23341218,03   
5     1141137,32     866346,18    1440978,95    1426659,48    1475551,38   
6     4984482,09    5511002,46    4927934,22    5445602,28    5413710,38   
7    14809416,46   14505727,38   14908091,32   15784899,40   15195312,89   
8    10775976,33   10398360,88   10528253,88   11040107,92   10549176,40   
9    30676457,06   30604453,47   31272395,18   30925391,36   27851438,72   
10   10855108,50   11160168,19   10475071,38   11386349,96   10640817,47   
11   12653528,76   12215107,11   12256928,49   12755413,77   12872578,37   
12   34806197,97   32147987,35   32239094,89   32685640,76   35457038,66   
13    9090794,82    9338771,45   10068210,08    9887061,61    9373432,00   
14    5046063,36    4741151,56    5401259,63    5521904,44    5238398,50   
15   39026934,13   42949566,82   47025972,04   47481695,17   46931248,28   
16   77136537,58   80554440,63   94758522,83   85360064,11   84722528,10   
17   11253833,56   10198619,17   13364258,29   13035374,08   12588595,77   
18   44054604,82   44911021,15   48056212,24   49872379,35   50912706,60   
19  161227125,43  187119397,64  187291126,07  194398399,48  184854516,35   
20   52460306,69   54419620,71   57811688,48   58094241,83   56982774,90   
21   27181488,26   26845308,18   29909762,04   30789135,84   31250854,33   
22   56673338,49   48397733,07   52413429,62   56636376,98   56113054,70   
23    8797487,68    9770421,80   10905392,18   10249299,82    9671553,45   
24    8794109,79    9231645,40   10221763,77    9163314,28    9243148,81   
25   20921212,45   216159

In [18]:
id = '1-3WrmxwGWO8jDg2-OvmC9lHtdXTBjxOF'
url = f'https://drive.google.com/uc?id={id}'

#df.to_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/datos_sus_limpios.csv', index=False, encoding= 'ISO-8859-1', sep=';' )

pd.read_csv(url, encoding= 'ISO-8859-1', sep= ';')

Unidade da Federação      2008/Jan      2008/Fev      2008/Mar  \
0              Rondônia    1388528,39    2931283,42    1541682,52   
1                  Acre     902416,00    1497206,26    1794028,48   
2              Amazonas    4735529,42    7118990,57    8196635,49   
3               Roraima     657889,53     777939,31     718688,03   
4                  Pará   18864744,11   19553758,20   21937342,70   
5                 Amapá    1120973,34    1268740,33     974651,24   
6             Tocantins    3441592,69    4985688,85    6205612,60   
7              Maranhão   10723506,39   13559679,41   13985142,36   
8                 Piauí    7985142,43   10079928,25   10298372,45   
9                 Ceará   15539821,90   25735101,55   28724625,75   
10  Rio Grande do Norte    5947814,08    9509755,83   10352238,59   
11              Paraíba   10723002,45   11386274,47   12053643,87   
12           Pernambuco   14393949,89   24181400,95   29991302,71   
13              Alagoas    6243726,32    8376622,16    8408336,22   
14              Sergipe    2780750,11    3676483,16    5051473,61   
15                Bahia   21211522,47   28189304,95   34181483,52   
16         Minas Gerais   45671659,76   70194037,10   79231336,95   
17       Espírito Santo    5456723,98    9102212,86   10249595,97   
18       Rio de Janeiro   23025258,52   28394310,93   44567062,94   
19            São Paulo   91678473,48  148677526,82  156087269,23   
20               Paraná   38266347,46   55384670,52   53801318,85   
21       Santa Catarina   16504913,45   25651429,11   26743524,89   
22    Rio Grande do Sul   30931325,46   57363420,01   51547794,07   
23   Mato Grosso do Sul    5377392,11    7002472,61    8423933,19   
24          Mato Grosso    4795299,01    8684882,23    7886243,14   
25                Goiás   15310637,29   22258668,68   21442515,75   
26     Distrito Federal    4745919,19    7632480,67    9647203,26   
27                Total  408424859,23  613174269,21  664043058,38   

        2008/Abr      2008/Mai      2008/Jun      2008/Jul      2008/Ago  \
0     1525314,96    1645953,84    1406150,68    3065279,01    3231494,61   
1     1730469,42    1819443,92    1828496,00    2511754,59    2089107,14   
2     8259378,42    7831399,90    8477273,62    9368858,72    9352532,70   
3      839994,39     862347,96     832440,66     996693,09     894271,18   
4    20842829,69   23249952,88   23240687,56   24002223,56   23341218,03   
5     1141137,32     866346,18    1440978,95    1426659,48    1475551,38   
6     4984482,09    5511002,46    4927934,22    5445602,28    5413710,38   
7    14809416,46   14505727,38   14908091,32   15784899,40   15195312,89   
8    10775976,33   10398360,88   10528253,88   11040107,92   10549176,40   
9    30676457,06   30604453,47   31272395,18   30925391,36   27851438,72   
10   10855108,50   11160168,19   10475071,38   11386349,96   10640817,47   
11   12653528,76   12215107,11   12256928,49   12755413,77   12872578,37   
12   34806197,97   32147987,35   32239094,89   32685640,76   35457038,66   
13    9090794,82    9338771,45   10068210,08    9887061,61    9373432,00   
14    5046063,36    4741151,56    5401259,63    5521904,44    5238398,50   
15   39026934,13   42949566,82   47025972,04   47481695,17   46931248,28   
16   77136537,58   80554440,63   94758522,83   85360064,11   84722528,10   
17   11253833,56   10198619,17   13364258,29   13035374,08   12588595,77   
18   44054604,82   44911021,15   48056212,24   49872379,35   50912706,60   
19  161227125,43  187119397,64  187291126,07  194398399,48  184854516,35   
20   52460306,69   54419620,71   57811688,48   58094241,83   56982774,90   
21   27181488,26   26845308,18   29909762,04   30789135,84   31250854,33   
22   56673338,49   48397733,07   52413429,62   56636376,98   56113054,70   
23    8797487,68    9770421,80   10905392,18   10249299,82    9671553,45   
24    8794109,79    9231645,40   10221763,77    9163314,28    9243148,81   
25   20921212,45   216159

# Aula 2 - Leyendo Archivos EXCEL

## Importando archivos Excel

In [19]:
id = '1q7kPRTisGsrQrj8l03oDj4IqrU2rzR8a'
url2 = f'https://drive.google.com/uc?export=download&id={id}'


df_excel = pd.read_excel(url2)
df_excel

País ISO 3166-1 alpha-3   Año         Total        Carbón  \
0      Afganistán                AFG  1750  0.000000e+00           NaN   
1      Afganistán                AFG  1751  0.000000e+00           NaN   
2      Afganistán                AFG  1752  0.000000e+00           NaN   
3      Afganistán                AFG  1753  0.000000e+00           NaN   
4      Afganistán                AFG  1754  0.000000e+00           NaN   
...           ...                ...   ...           ...           ...   
63099      Global                WLD  2017  3.609674e+10  1.450697e+10   
63100      Global                WLD  2018  3.682651e+10  1.474683e+10   
63101      Global                WLD  2019  3.708256e+10  1.472598e+10   
63102      Global                WLD  2020  3.526409e+10  1.417456e+10   
63103      Global                WLD  2021  3.712385e+10  1.497960e+10   

             Aceite           Gas       Cemento        Quema        Otros  \
0               NaN           NaN           NaN          NaN          NaN   
1               NaN           NaN           NaN          NaN          NaN   
2               NaN           NaN           NaN          NaN          NaN   
3               NaN           NaN           NaN          NaN          NaN   
4               NaN           NaN           NaN          NaN          NaN   
...             ...           ...           ...          ...          ...   
63099  1.224263e+10  7.144928e+09  1.507923e+09  391992176.0  302294047.0   
63100  1.226602e+10  7.529847e+09  1.569218e+09  412115746.0  302478706.0   
63101  1.234565e+10  7.647528e+09  1.617507e+09  439253991.0  306638573.0   
63102  1.119181e+10  7.556290e+09  1.637538e+09  407583673.0  296301685.0   
63103  1.183716e+10  7.921829e+09  1.672592e+09  416525563.0  296145746.0   

       Per Capita  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             NaN  
...           ...  
63099   4749682.0  
63100   4792753.0  
63101   4775633.0  
63102   4497423.0  
63103   4693699.0  

[63104 rows x 11 columns]

In [20]:
pd.ExcelFile(url2).sheet_names  # Nos muestra el nombre de las hojas del archivo

['emisiones_C02', 'emisiones_percapita', 'fuentes']

In [21]:
pd.read_excel(url2, sheet_name=2) # Se pued usar el nombre también

País ISO 3166-1 alpha-3   Año  \
0      Afganistán                AFG  1750   
1      Afganistán                AFG  1751   
2      Afganistán                AFG  1752   
3      Afganistán                AFG  1753   
4      Afganistán                AFG  1754   
...           ...                ...   ...   
63099      Global                WLD  2017   
63100      Global                WLD  2018   
63101      Global                WLD  2019   
63102      Global                WLD  2020   
63103      Global                WLD  2021   

                                      Total             Carbón  \
0                                    [NONE]             [NONE]   
1                                    [NONE]             [NONE]   
2                                    [NONE]             [NONE]   
3                                    [NONE]             [NONE]   
4                                    [NONE]             [NONE]   
...                                     ...                ...   
63099  CDIAC 2022, BP, and Sum of countries  CDIAC 2022 and BP   
63100  CDIAC 2022, BP, and Sum of countries  CDIAC 2022 and BP   
63101  CDIAC 2022, BP, and Sum of countries  CDIAC 2022 and BP   
63102  CDIAC 2022, BP, and Sum of countries  CDIAC 2022 and BP   
63103  CDIAC 2022, BP, and Sum of countries  CDIAC 2022 and BP   

                  Aceite                Gas        Cemento  \
0                 [NONE]             [NONE]         [NONE]   
1                 [NONE]             [NONE]         [NONE]   
2                 [NONE]             [NONE]         [NONE]   
3                 [NONE]             [NONE]         [NONE]   
4                 [NONE]             [NONE]         [NONE]   
...                  ...                ...            ...   
63099  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63100  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63101  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63102  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63103  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   

                    Quema   Otros  \
0                  [NONE]  [NONE]   
1                  [NONE]  [NONE]   
2                  [NONE]  [NONE]   
3                  [NONE]  [NONE]   
4                  [NONE]  [NONE]   
...                   ...     ...   
63099  CDIAC 2022 and GCP  [NONE]   
63100  CDIAC 2022 and GCP  [NONE]   
63101  CDIAC 2022 and GCP  [NONE]   
63102  CDIAC 2022 and GCP  [NONE]   
63103  CDIAC 2022 and GCP  [NONE]   

                                              Per Capita  
0                                                 [NONE]  
1                                                 [NONE]  
2                                                 [NONE]  
3                                                 [NONE]  
4                                                 [NONE]  
...                                                  ...  
63099  CDIAC 2022, BP, Sum of countries, and UN popul...  
63100  CDIAC 2022, BP, Sum of countries, and UN popul...  
63101  CDIAC 2022, BP, Sum of countries, and UN popul...  
63102  CDIAC 2022, BP, Sum of countries, and UN popul...  
63103  CDIAC 2022, BP, Sum of countries, and UN popul...  

[63104 rows x 11 columns]

In [22]:
numeros_cols = pd.read_excel(url2, usecols=[0, 2, 3, 4])
numeros_cols

País   Año         Total        Carbón
0      Afganistán  1750  0.000000e+00           NaN
1      Afganistán  1751  0.000000e+00           NaN
2      Afganistán  1752  0.000000e+00           NaN
3      Afganistán  1753  0.000000e+00           NaN
4      Afganistán  1754  0.000000e+00           NaN
...           ...   ...           ...           ...
63099      Global  2017  3.609674e+10  1.450697e+10
63100      Global  2018  3.682651e+10  1.474683e+10
63101      Global  2019  3.708256e+10  1.472598e+10
63102      Global  2020  3.526409e+10  1.417456e+10
63103      Global  2021  3.712385e+10  1.497960e+10

[63104 rows x 4 columns]

In [23]:
intervalo_cols = pd.read_excel(url2, usecols='A:D')
intervalo_cols

País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [24]:
nombre_cols = pd.read_excel(url2, usecols=['País', 'Año', 'Total'])
nombre_cols

País   Año         Total
0      Afganistán  1750  0.000000e+00
1      Afganistán  1751  0.000000e+00
2      Afganistán  1752  0.000000e+00
3      Afganistán  1753  0.000000e+00
4      Afganistán  1754  0.000000e+00
...           ...   ...           ...
63099      Global  2017  3.609674e+10
63100      Global  2018  3.682651e+10
63101      Global  2019  3.708256e+10
63102      Global  2020  3.526409e+10
63103      Global  2021  3.712385e+10

[63104 rows x 3 columns]

In [25]:
nombre_cols = pd.read_excel(url2, usecols=['País', 'Año', 'Total'], nrows=10)
nombre_cols

País   Año  Total
0  Afganistán  1750      0
1  Afganistán  1751      0
2  Afganistán  1752      0
3  Afganistán  1753      0
4  Afganistán  1754      0
5  Afganistán  1755      0
6  Afganistán  1756      0
7  Afganistán  1757      0
8  Afganistán  1758      0
9  Afganistán  1759      0

In [26]:
#numeros_cols.to_excel('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/emisiones_CO2_resumen.xlsx', index=False)

id = '1-6CGpag7RIMTucelo4F4rETr2-b_lEXb'
url = f'https://drive.google.com/uc?export=download&id={id}'
pd.read_excel(url)


País   Año         Total        Carbón
0      Afganistán  1750  0.000000e+00           NaN
1      Afganistán  1751  0.000000e+00           NaN
2      Afganistán  1752  0.000000e+00           NaN
3      Afganistán  1753  0.000000e+00           NaN
4      Afganistán  1754  0.000000e+00           NaN
...           ...   ...           ...           ...
63099      Global  2017  3.609674e+10  1.450697e+10
63100      Global  2018  3.682651e+10  1.474683e+10
63101      Global  2019  3.708256e+10  1.472598e+10
63102      Global  2020  3.526409e+10  1.417456e+10
63103      Global  2021  3.712385e+10  1.497960e+10

[63104 rows x 4 columns]

## Leyendo Datos de GHoogle Sheets

In [27]:
sheet_id = '1qD-MYh0hXFb_C5zmgrMKSgB0DFR4C7-SvPsuOubdyEA'
sheet_name = 'emisiones_percapita'
url_sheet = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

datos = pd.read_csv(url_sheet)
datos



País ISO 3166-1 alpha-3   Año           Total          Carbón  \
0      Afganistán                AFG  1750               0             NaN   
1      Afganistán                AFG  1751               0             NaN   
2      Afganistán                AFG  1752               0             NaN   
3      Afganistán                AFG  1753               0             NaN   
4      Afganistán                AFG  1754               0             NaN   
...           ...                ...   ...             ...             ...   
63099      Global                WLD  2017  36.096.739.276  14.506.973.805   
63100      Global                WLD  2018  36.826.506.600  14.746.830.688   
63101      Global                WLD  2019  37.082.558.969  14.725.978.025   
63102      Global                WLD  2020  35.264.085.734  14.174.564.010   
63103      Global                WLD  2021  37.123.850.352  14.979.598.083   

               Aceite            Gas        Cemento        Quema        Otros  \
0                 NaN            NaN            NaN          NaN          NaN   
1                 NaN            NaN            NaN          NaN          NaN   
2                 NaN            NaN            NaN          NaN          NaN   
3                 NaN            NaN            NaN          NaN          NaN   
4                 NaN            NaN            NaN          NaN          NaN   
...               ...            ...            ...          ...          ...   
63099  12.242.627.935  7.144.928.128  1.507.923.185  391.992.176  302.294.047   
63100  12.266.016.285  7.529.846.784  1.569.218.392  412.115.746  302.478.706   
63101  12.345.653.374  7.647.528.220  1.617.506.786  439.253.991  306.638.573   
63102  11.191.808.551  7.556.290.283  1.637.537.532  407.583.673  296.301.685   
63103  11.837.159.116  7.921.829.472  1.672.592.372  416.525.563  296.145.746   

      Per Capita  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
63099  4.749.682  
63100  4.792.753  
63101  4.775.633  
63102  4.497.423  
63103  4.693.699  

[63104 rows x 11 columns]

In [28]:
url_sheet = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

datos_percapita = pd.read_csv(url_sheet)
datos_percapita

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
0      Afganistán                AFG  1750        NaN        NaN        NaN   
1      Afganistán                AFG  1751        NaN        NaN        NaN   
2      Afganistán                AFG  1752        NaN        NaN        NaN   
3      Afganistán                AFG  1753        NaN        NaN        NaN   
4      Afganistán                AFG  1754        NaN        NaN        NaN   
...           ...                ...   ...        ...        ...        ...   
63099      Global                WLD  2017  4.749.682  1.908.857  1.610.910   
63100      Global                WLD  2018  4.792.753  1.919.213  1.596.350   
63101      Global                WLD  2019  4.775.633  1.896.468  1.589.920   
63102      Global                WLD  2020  4.497.423  1.807.760  1.427.353   
63103      Global                WLD  2021  4.693.699  1.893.923  1.496.614   

             Gas  Cemento   Quema   Otros  
0            NaN      NaN     NaN     NaN  
1            NaN      NaN     NaN     NaN  
2            NaN      NaN     NaN     NaN  
3            NaN      NaN     NaN     NaN  
4            NaN      NaN     NaN     NaN  
...          ...      ...     ...     ...  
63099    940.144  198.416  51.579  39.776  
63100    979.965  204.225  53.634  39.366  
63101    984.878  208.309  56.569  39.490  
63102    963.695  208.844  51.981  37.789  
63103  1.001.585  211.472  52.663  37.443  

[63104 rows x 10 columns]

In [29]:
# datos_percapita.to_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/emisiones_percapita.csv', index=False)
id = '1-B-Ri3UN8km0V-E6WWDBf1pZiyzu0ADw'
pd.read_csv(f'https://drive.google.com/uc?id={id}')

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
0      Afganistán                AFG  1750        NaN        NaN        NaN   
1      Afganistán                AFG  1751        NaN        NaN        NaN   
2      Afganistán                AFG  1752        NaN        NaN        NaN   
3      Afganistán                AFG  1753        NaN        NaN        NaN   
4      Afganistán                AFG  1754        NaN        NaN        NaN   
...           ...                ...   ...        ...        ...        ...   
63099      Global                WLD  2017  4.749.682  1.908.857  1.610.910   
63100      Global                WLD  2018  4.792.753  1.919.213  1.596.350   
63101      Global                WLD  2019  4.775.633  1.896.468  1.589.920   
63102      Global                WLD  2020  4.497.423  1.807.760  1.427.353   
63103      Global                WLD  2021  4.693.699  1.893.923  1.496.614   

             Gas  Cemento   Quema   Otros  
0            NaN      NaN     NaN     NaN  
1            NaN      NaN     NaN     NaN  
2            NaN      NaN     NaN     NaN  
3            NaN      NaN     NaN     NaN  
4            NaN      NaN     NaN     NaN  
...          ...      ...     ...     ...  
63099    940.144  198.416  51.579  39.776  
63100    979.965  204.225  53.634  39.366  
63101    984.878  208.309  56.569  39.490  
63102    963.695  208.844  51.981  37.789  
63103  1.001.585  211.472  52.663  37.443  

[63104 rows x 10 columns]

# Aula 3 - Leyendo Archivos JSON

## Importando archivos JSON

In [30]:
id = '1cN_QIoyXw9UsJ-ZVkWInDMzCgabFZGNu'
url_json = f'https://drive.google.com/uc?id={id}'
id2 = '1i2t_EhLcFmH5zVsOqOY_Er2OpYOyhO_g'
url_json2 = f'https://drive.google.com/uc?id={id2}'

In [31]:
pacientes = pd.read_json(url_json)
pacientes

ID_paciente Enfermedad_corazon    IMC Fumador Consumo_alcohol AVC  \
0              0                 No  16.60      Sí              No  No   
1              1                 No  20.34      No              No  Sí   
2              2                 No  26.58      Sí              No  No   
3              3                 No  24.21      No              No  No   
4              4                 No  23.71      No              No  No   
..           ...                ...    ...     ...             ...  ..   
995          995                 No  28.29      Sí              No  No   
996          996                 No  25.69      Sí              No  No   
997          997                 Sí  26.99      No              No  No   
998          998                 No  44.29      No              No  No   
999          999                 No  25.83      No              No  No   

     Salud_fisica  Salud_mental Dificultad_caminar Sexo_biologico Rango_edad  \
0               3            30                 No       Femenino      55-59   
1               0             0                 No       Femenino     80 ó +   
2              20            30                 No      Masculino      65-69   
3               0             0                 No       Femenino      75-79   
4              28             0                 Sí       Femenino      40-44   
..            ...           ...                ...            ...        ...   
995            10            20                 No       Femenino      65-69   
996             0             0                 No       Femenino      75-79   
997             1             0                 No      Masculino      70-74   
998            30             0                 Sí       Femenino      70-74   
999             0             0                 No      Masculino      70-74   

       Raza Diabetes Actividad_fisica Salud_general  Horas_sueño Asma  \
0    Blanca       Sí               Sí     Muy buena            5   Sí   
1    Blanca       No               Sí     Muy buena            7   No   
2    Blanca       Sí               Sí     Razonable            8   Sí   
3    Blanca       No               No         Buena            6   No   
4    Blanca       No               Sí     Muy buena            8   No   
..      ...      ...              ...           ...          ...  ...   
995   Negra       Sí               Sí     Razonable            8   No   
996  Blanca       No               Sí     Excelente            8   No   
997  Blanca       No               Sí     Muy buena            8   No   
998  Blanca       Sí               No         Buena            6   Sí   
999   Negra       Sí               No     Excelente            7   No   

    Enfermedad_renal Cancer_piel  
0                 No          Sí  
1                 No          No  
2                 No          No  
3                 No          Sí  
4                 No          No  
..               ...         ...  
995               No          No  
996               No          No  
997               No          No  
998               No          No  
999               No          No  

[1000 rows x 19 columns]

In [32]:
pacientes_2 = pd.read_json(url_json2)
pacientes_2

Investigación   Año  \
0  Indicadores clave de enfermedades cardíacas  2020   
1  Indicadores clave de enfermedades cardíacas  2020   
2  Indicadores clave de enfermedades cardíacas  2020   

                                           Pacientes  
0  {'ID': '01', 'Rango_edad': '55-59', 'Sexo_biol...  
1  {'ID': '02', 'Rango_edad': '80 ó +', 'Sexo_bio...  
2  {'ID': '03', 'Rango_edad': '65-69', 'Sexo_biol...

Cuando el JSON posee diccionarios anidados, el metodo read no es efectivo

In [33]:
# import json

# with open(url_json2, 'r') as f:
#     data = json.load(f)

pacientes_2 = pd.json_normalize(pacientes_2['Pacientes'])
pacientes_2


ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

In [34]:
#pacientes.to_json('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/pacientes_exp.json')

id = '1JjRaCihoC_6NgC3tmps0OZNNWYfBiATT'
url_json = f'https://drive.google.com/uc?id={id}'

pd.read_json(url_json)

ID_paciente Enfermedad_corazon    IMC Fumador Consumo_alcohol AVC  \
0              0                 No  16.60      Sí              No  No   
1              1                 No  20.34      No              No  Sí   
2              2                 No  26.58      Sí              No  No   
3              3                 No  24.21      No              No  No   
4              4                 No  23.71      No              No  No   
..           ...                ...    ...     ...             ...  ..   
995          995                 No  28.29      Sí              No  No   
996          996                 No  25.69      Sí              No  No   
997          997                 Sí  26.99      No              No  No   
998          998                 No  44.29      No              No  No   
999          999                 No  25.83      No              No  No   

     Salud_fisica  Salud_mental Dificultad_caminar Sexo_biologico Rango_edad  \
0               3            30                 No       Femenino      55-59   
1               0             0                 No       Femenino     80 ó +   
2              20            30                 No      Masculino      65-69   
3               0             0                 No       Femenino      75-79   
4              28             0                 Sí       Femenino      40-44   
..            ...           ...                ...            ...        ...   
995            10            20                 No       Femenino      65-69   
996             0             0                 No       Femenino      75-79   
997             1             0                 No      Masculino      70-74   
998            30             0                 Sí       Femenino      70-74   
999             0             0                 No      Masculino      70-74   

       Raza Diabetes Actividad_fisica Salud_general  Horas_sueño Asma  \
0    Blanca       Sí               Sí     Muy buena            5   Sí   
1    Blanca       No               Sí     Muy buena            7   No   
2    Blanca       Sí               Sí     Razonable            8   Sí   
3    Blanca       No               No         Buena            6   No   
4    Blanca       No               Sí     Muy buena            8   No   
..      ...      ...              ...           ...          ...  ...   
995   Negra       Sí               Sí     Razonable            8   No   
996  Blanca       No               Sí     Excelente            8   No   
997  Blanca       No               Sí     Muy buena            8   No   
998  Blanca       Sí               No         Buena            6   Sí   
999   Negra       Sí               No     Excelente            7   No   

    Enfermedad_renal Cancer_piel  
0                 No          Sí  
1                 No          No  
2                 No          No  
3                 No          Sí  
4                 No          No  
..               ...         ...  
995               No          No  
996               No          No  
997               No          No  
998               No          No  
999               No          No  

[1000 rows x 19 columns]

In [35]:
# pacientes_2.to_json('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/pacientes_2_exp.json')

id = '1-31iN5BCcPuDqR7AwTyEfcAEcSpuYIbj'
url_json = f'https://drive.google.com/uc?id={id}'

pd.read_json(url_json)


ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0   1      55-59          Mujer  Blanca  16.60      Sí              No   
1   2     80 ó +          Mujer  Blanca  20.34      No              No   
2   3      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

## Cargando JSON desde una API

In [36]:
import requests
import json


In [37]:
datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [38]:
resultado = json.loads(datos_frutas.text)

In [39]:
pd.DataFrame(resultado)

name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

                 

In [40]:
df = pd.json_normalize(resultado)
df

name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

    nutritions.ca

# Aula 4 - Leyendo HTML y XML

## Importando archivos HTML


In [41]:
id = '10agwPgeoQvukIwSH8F4MsQX-xObhjse7'
url_html = f'https://drive.google.com/uc?id={id}'

pd.read_html(url_html)


[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   

El archivo tiene tres tablas y nosotros necesitamos la segunda

In [42]:
peliculas = pd.read_html(url_html)[1]
peliculas

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

In [43]:
# peliculas.to_html('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/peliculas.html', index=False)
id = '1-DtxdKy9kY2SXqQnJlpE9sDCiAaXPfxV'
url_html = f'https://drive.google.com/uc?id={id}'

pd.read_html(url_html)

[                            Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   ...   
 95                 The Searchers          1956             John Ford   
 96              Bringing Up Baby          1938          Howard Hawks   
 97                    Unforgiven          1992        Clint Eastwood   
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
 99           Yankee Doodle Dandy          1942        Michael Curtiz   
 
                       Production companies  Rank  
 0                       RKO Radio Pictures     1  
 1                

In [44]:
#peliculas.to_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/peliculas.csv', index=False)

id = '1-F4TQ6TlYJVXv-mXhGe-hFzZ_0XisXx8'
url_csv = f'https://drive.google.com/uc?id={id}'

pd.read_csv(url_csv)

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

## Importando archivos XML

In [45]:
id = '1GWtV-qt00912Be731jdxtQ4K9ms4kviy'
url_xml = f'https://drive.google.com/uc?id={id}'

#xml = '/content/drive/MyDrive/Pandas ES - BASES DE DATOS/imdb_top_1000.xml'

In [46]:
from io import BytesIO
import gdown

#pd.read_xml(xml)

output = 'imdb_top_1000.xml'
# Descargar el archivo sin pasar por la advertencia
gdown.download(f'{url_xml}', output, quiet=False)



Downloading...
From (original): https://drive.google.com/uc?id=1GWtV-qt00912Be731jdxtQ4K9ms4kviy
From (redirected): https://drive.google.com/uc?id=1GWtV-qt00912Be731jdxtQ4K9ms4kviy&confirm=t&uuid=5483795f-728b-4e46-8015-42658a70910e
To: /home/griselda/Documentos/Repositorios/Data_Science_Notebooks/2 - Aprendiendo a hacer ETL G8 - ONE/imdb_top_1000.xml
100%|██████████| 876k/876k [00:00<00:00, 4.24MB/s]


'imdb_top_1000.xml'

In [47]:
datos_xml = pd.read_xml(output)
datos_xml

index                                        Poster_Link  \
0        0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1        1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2        2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3        3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4        4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..     ...                                                ...   
995    995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996    996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997    997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998    998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999    999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2             The Dark Knight          2008          UA  152 min   
3      The Godfather: Part II          1974           A  202 min   
4                12 Angry Men          1957           U   96 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944        None   97 min   
999              The 39 Steps          1935        None   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2        Action, Crime, Drama          9.0   
3                Crime, Drama          9.0   
4                Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2       Christopher Nolan     Christian Bale       Heath Ledger   
3    Francis Ford Coppola          Al Pacino     Robert De Niro   
4            Sidney Lumet        Henry Fonda        Lee J. Cobb   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  
0        Bob Gunton  William Sadler      2343110   28,341,469  
1        James Caan    Diane Keaton      1620367  134,966,411  
2     Aaron Eckh

In [49]:
# datos_xml.to_xml('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/datos_xml.xml', index=False)
#pd.read_xml('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/datos_xml.xml')

id = '1-FOJrsRr0xsvJcBXXrYTmd0hhShKcSeZ'
url_xml = f'https://drive.google.com/uc?id={id}'

output = 'datos.xml'
# Descargar el archivo sin pasar por la advertencia
gdown.download(f'{url_xml}', output, quiet=False)
datos_xml = pd.read_xml(output)
datos_xml

Downloading...
From (original): https://drive.google.com/uc?id=1-FOJrsRr0xsvJcBXXrYTmd0hhShKcSeZ
From (redirected): https://drive.google.com/uc?id=1-FOJrsRr0xsvJcBXXrYTmd0hhShKcSeZ&confirm=t&uuid=843e2121-898b-4881-bd99-a05a63053331
To: /home/griselda/Documentos/Repositorios/Data_Science_Notebooks/2 - Aprendiendo a hacer ETL G8 - ONE/datos.xml
100%|██████████| 876k/876k [00:00<00:00, 4.04MB/s]


index                                        Poster_Link  \
0        0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1        1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2        2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3        3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4        4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..     ...                                                ...   
995    995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996    996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997    997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998    998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999    999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2             The Dark Knight          2008          UA  152 min   
3      The Godfather: Part II          1974           A  202 min   
4                12 Angry Men          1957           U   96 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944        None   97 min   
999              The 39 Steps          1935        None   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2        Action, Crime, Drama          9.0   
3                Crime, Drama          9.0   
4                Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2       Christopher Nolan     Christian Bale       Heath Ledger   
3    Francis Ford Coppola          Al Pacino     Robert De Niro   
4            Sidney Lumet        Henry Fonda        Lee J. Cobb   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  
0        Bob Gunton  William Sadler      2343110   28,341,469  
1        James Caan    Diane Keaton      1620367  134,966,411  
2     Aaron Eckh

In [50]:
#datos_xml.to_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/datos_imdb.csv', index=False)
#pd.read_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/datos_imdb.csv')

id ='1-HpNM2Z_e9RxYRu8_-EoQuV8jg8-vgGg'
url = f'https://drive.google.com/uc?id={id}'

pd.read_csv(url)

index                                        Poster_Link  \
0        0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1        1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2        2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3        3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4        4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   
..     ...                                                ...   
995    995  https://m.media-amazon.com/images/M/MV5BNGEwMT...   
996    996  https://m.media-amazon.com/images/M/MV5BODk3Yj...   
997    997  https://m.media-amazon.com/images/M/MV5BM2U3Yz...   
998    998  https://m.media-amazon.com/images/M/MV5BZTBmMj...   
999    999  https://m.media-amazon.com/images/M/MV5BMTY5OD...   

                 Series_Title Released_Year Certificate  Runtime  \
0    The Shawshank Redemption          1994           A  142 min   
1               The Godfather          1972           A  175 min   
2             The Dark Knight          2008          UA  152 min   
3      The Godfather: Part II          1974           A  202 min   
4                12 Angry Men          1957           U   96 min   
..                        ...           ...         ...      ...   
995    Breakfast at Tiffany's          1961           A  115 min   
996                     Giant          1956           G  201 min   
997     From Here to Eternity          1953      Passed  118 min   
998                  Lifeboat          1944         NaN   97 min   
999              The 39 Steps          1935         NaN   86 min   

                        Genre  IMDB_Rating  \
0                       Drama          9.3   
1                Crime, Drama          9.2   
2        Action, Crime, Drama          9.0   
3                Crime, Drama          9.0   
4                Crime, Drama          9.0   
..                        ...          ...   
995    Comedy, Drama, Romance          7.6   
996            Drama, Western          7.6   
997       Drama, Romance, War          7.6   
998                Drama, War          7.6   
999  Crime, Mystery, Thriller          7.6   

                                              Overview  Meta_score  \
0    Two imprisoned men bond over a number of years...        80.0   
1    An organized crime dynasty's aging patriarch t...       100.0   
2    When the menace known as the Joker wreaks havo...        84.0   
3    The early life and career of Vito Corleone in ...        90.0   
4    A jury holdout attempts to prevent a miscarria...        96.0   
..                                                 ...         ...   
995  A young New York socialite becomes interested ...        76.0   
996  Sprawling epic covering the life of a Texas ca...        84.0   
997  In Hawaii in 1941, a private is cruelly punish...        85.0   
998  Several survivors of a torpedoed merchant ship...        78.0   
999  A man in London tries to help a counter-espion...        93.0   

                 Director              Star1              Star2  \
0          Frank Darabont        Tim Robbins     Morgan Freeman   
1    Francis Ford Coppola      Marlon Brando          Al Pacino   
2       Christopher Nolan     Christian Bale       Heath Ledger   
3    Francis Ford Coppola          Al Pacino     Robert De Niro   
4            Sidney Lumet        Henry Fonda        Lee J. Cobb   
..                    ...                ...                ...   
995         Blake Edwards     Audrey Hepburn     George Peppard   
996        George Stevens   Elizabeth Taylor        Rock Hudson   
997        Fred Zinnemann     Burt Lancaster   Montgomery Clift   
998      Alfred Hitchcock  Tallulah Bankhead        John Hodiak   
999      Alfred Hitchcock       Robert Donat  Madeleine Carroll   

              Star3           Star4  No_of_Votes        Gross  
0        Bob Gunton  William Sadler      2343110   28,341,469  
1        James Caan    Diane Keaton      1620367  134,966,411  
2     Aaron Eckh

## Ejercicio

Obtener un DataFrame de la tabla que contiene la información del número de habitantes de cada país de la página de Wikipedia https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n

In [52]:
url_wikipedia = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n'

html = pd.read_html(url_wikipedia)
len(html)

7

In [53]:
poblacion = html[0]

In [54]:
poblacion

N.º                   País (o territorio dependiente)  \
0      1                                             India   
1      2                                        China[12]​   
2      3                                    Estados Unidos   
3      4                                         Indonesia   
4      5                                          Pakistán   
..   ...                                               ...   
241  242                           Islas Cocos (Australia)   
242  243  Islas Ultramarinas Menores de los Estados Unidos   
243  244                               Islas Pitcairn (RU)   
244  NaN                                             Mundo   
245   N°                   País (o territorio dependiente)   

    Proyección exponencial de la población al 1/7/2025[7]​  \
0                                        1 417 492 000       
1                                        1 407 934 000       
2                                          342 181 000       
3                                          285 783 000       
4                                          256 204 000       
..                                                 ...       
241                                                600       
242                                                100       
243                                                 30       
244                                      8 084 481 000       
245  Proyección exponencial de la población al 1/7/...       

     Total mun- dial (%) Cambio medio anual (%)[8]​  \
0                   1753                        090   
1                   1742                       -005   
2                    423                        061   
3                    353                        117   
4                    317                        256   
..                   ...                        ...   
241                  000                        174   
242                  000                       -496   
243                  000                       -111   
244                10000                        103   
245  Total mun- dial (%)     Cambio medio anual (%)   

     Cambio absoluto anual promedio  Cambio medio abs. total anual (%)  \
0                        12 692 000                               1518   
1                        -1 390 000                                  -   
2                         2 084 000                                249   
3                         3 337 000                                399   
4                         6 567 000                                786   
..                              ...                                ...   
241                               0                                000   
242                               0                                000   
243                               0                                000   
244                      83 594 000                              10000   
245  Cambio absoluto anual promedio  Cambio medio abs. total anual (%)   

    Años para even- tual du- pli- ca- ción[9]​  \
0                                           78   
1                                            -   
2                                          114   
3                                           60   
4                                           27   
..                                         ...   
241                                         40   
242                                          -   
243                                          -   
244                                         68   
245     Años para even- tual du- pli- ca- ción   

    Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional  \
0                                        1 417 492 000                                                  
1                                        1 408 280 000                                                  
2                                          342 08

In [57]:
# poblacion.to_html('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/poblacion.html', index=False)
# pd.read_html('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/poblacion.html')

id = '1-I0MBazg-Gs9j7zFWPcA0bhKc2NPon2e'
url = f'https://drive.google.com/uc?id={id}'

pd.read_html(url, encoding='utf-8', decimal=',', thousands='.')

[     N.º                   País (o territorio dependiente)  \
 0      1                                             India   
 1      2                                        China[12]​   
 2      3                                    Estados Unidos   
 3      4                                         Indonesia   
 4      5                                          Pakistán   
 ..   ...                                               ...   
 241  242                           Islas Cocos (Australia)   
 242  243  Islas Ultramarinas Menores de los Estados Unidos   
 243  244                               Islas Pitcairn (RU)   
 244  NaN                                             Mundo   
 245   N°                   País (o territorio dependiente)   
 
     Proyección exponencial de la población al 1/7/2025[7]​  \
 0                                        1 417 492 000       
 1                                        1 407 934 000       
 2                                          342 181 0

In [58]:
#poblacion.to_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/poblacion.csv', index=False)
#pd.read_csv('/content/drive/MyDrive/Pandas ES - BASES DE DATOS/poblacion.csv')

id = '1-IEfrrHVB_UyCudxg-n1MPwdn2_c7QN7'
url = f'https://drive.google.com/uc?id={id}'

pd.read_csv(url)

N.º                   País (o territorio dependiente)  \
0      1                                             India   
1      2                                        China[12]​   
2      3                                    Estados Unidos   
3      4                                         Indonesia   
4      5                                          Pakistán   
..   ...                                               ...   
241  242                           Islas Cocos (Australia)   
242  243  Islas Ultramarinas Menores de los Estados Unidos   
243  244                               Islas Pitcairn (RU)   
244  NaN                                             Mundo   
245   N°                   País (o territorio dependiente)   

    Proyección exponencial de la población al 1/7/2025[7]​  \
0                                        1 417 492 000       
1                                        1 407 934 000       
2                                          342 181 000       
3                                          285 783 000       
4                                          256 204 000       
..                                                 ...       
241                                                600       
242                                                100       
243                                                 30       
244                                      8 083 458 000       
245  Proyección exponencial de la población al 1/7/...       

     Total mun- dial (%) Cambio medio anual (%)[8]​  \
0                   1754                        090   
1                   1742                       -005   
2                    423                        061   
3                    354                        117   
4                    317                        256   
..                   ...                        ...   
241                  000                        174   
242                  000                       -496   
243                  000                       -111   
244                10000                        103   
245  Total mun- dial (%)     Cambio medio anual (%)   

     Cambio absoluto anual promedio  Cambio medio abs. total anual (%)  \
0                        12 692 000                               1523   
1                        -1 390 000                                  -   
2                         2 084 000                                250   
3                         3 337 000                                400   
4                         6 567 000                                788   
..                              ...                                ...   
241                               0                                000   
242                               0                                000   
243                               0                                000   
244                      83 362 000                              10000   
245  Cambio absoluto anual promedio  Cambio medio abs. total anual (%)   

    Años para even- tual du- pli- ca- ción[9]​  \
0                                           78   
1                                            -   
2                                          114   
3                                           60   
4                                           27   
..                                         ...   
241                                         40   
242                                          -   
243                                          -   
244                                         68   
245     Años para even- tual du- pli- ca- ción   

    Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional  \
0                                        1 417 492 000                                                  
1                                        1 408 280 000                                                  
2                                          341 76

# Leyendo Banco de Datos

## Creando un banco de datos local

In [59]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [60]:
engine = create_engine('sqlite:///:memory:')

In [61]:
id = '1fT_GbEIDmeF9yinfd2HuDTNEZTQVP-Ey'
url = f'https://drive.google.com/uc?id={id}'
clientes = pd.read_csv(url)
clientes

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

In [62]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS clientes"))  #Este código es por si hay que volver a crear la tabla

clientes.to_sql('clientes', engine, index=False)

438463

In [63]:
inspector = inspect(engine)
inspector.get_table_names()

['clientes']

## Leyendo una consulta SQL

In [64]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta ="Empleado"'

In [65]:
empleados = pd.read_sql(sql = text(query), con = engine.connect())

In [66]:
empleados

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [ ]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS empleados"))  #Este código es por si hay que volver a crear la tabla
empleados.to_sql('empleados', engine, index=False)

226059

In [ ]:
pd.read_sql_table('empleados', engine)

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008815    46    Nivel superior            Casado               2   
4          5112956    46    Nivel superior            Casado               2   
...            ...   ...               ...               ...             ...   
226054     6837905    43  Nivel intermedio            Casado               3   
226055     6837906    43  Nivel intermedio            Casado               3   
226056     6839936    34  Nivel intermedio            Casado               3   
226057     6840222    43  Nivel intermedio           Soltero               1   
226058     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3                Empleado        Contabilidad              2   
4                Empleado        Contabilidad              2   
...                   ...                 ...            ...   
226054           Empleado                Otro              7   
226055           Empleado                Otro              7   
226056           Empleado  Construcción Civil              5   
226057           Empleado  Construcción Civil              8   
226058           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            1  Casa/Departamento propio  
4                270000.0            1  Casa/Departamento propio  
...                   ...          ...                       ...  
226054           355050.0            1  Casa/Departamento propio  
226055           355050.0            1  Casa/Departamento propio  
226056           135000.0            1  Casa/Departamento propio  
226057           103500.0            0  Casa/Departamento propio  
226058           121500.0            0  Casa/Departamento propio  

[226059 rows x 11 columns]

In [ ]:
pd.read_sql_table('empleados', engine, columns=['ID_Cliente', 'Grado_estudio', 'Rendimiento_anual'])

ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

In [ ]:
query = 'SELECT * FROM clientes'

In [ ]:
pd.read_sql(sql = text(query), con = engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

### Borrando registros

In [ ]:
from sqlalchemy.exc import SQLAlchemyError

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('Se borró el registro', r_set.rowcount)

Se borró el registro 1


In [ ]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008805    32    Nivel superior  Relación-estable               2   
1          5008806    58  Nivel intermedio            Casado               2   
2          5008808    52  Nivel intermedio           Soltero               1   
3          5008809    52  Nivel intermedio           Soltero               1   
4          5008810    52    Nivel superior           Soltero               1   
...            ...   ...               ...               ...             ...   
438457     6840104    62  Nivel intermedio        Divorciado               1   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado           Seguridad              3   
2        Business Partner              Ventas              8   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438457        Pensionista                Otro              0   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                112500.0            1  Casa/Departamento propio  
2                270000.0            0  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438457           135000.0            0  Casa/Departamento propio  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  

[438462 rows x 11 columns]

### Actualizar registros

In [ ]:
query = 'UPDATE clientes SET Grado_estudio = "Nivel superior" WHERE ID_Cliente=5008810'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('Se actualizó el registro', r_set.rowcount)

Se actualizó el registro 1


## Ejercicio


* Crear la base de datos local con la biblioteca SQLAlchemy.
* Escribir los datos del archivo CSV en esta base de datos local.
* Realizar tres actualizaciones en la base de datos:
 * Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
 * Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.
 * Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:
   * ID_cliente: 6850985
   * Edad: 33
   * Grado_estudio: Doctorado
   * Estado_civil: Soltero
   * Tamaño_familia: 1
   * Categoria_de_renta: Empleado
   * Ocupacion: TI
   * Años_empleado: 2
   * Rendimiento_anual: 290000
   * Tiene_carro: 0
   * Vivienda: Casa/Departamento propio

Consejo importante: Para agregar un nuevo cliente a la tabla, use la cláusula **INSERT INTO** seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula **VALUES** y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

In [ ]:
query = 'SELECT * FROM clientes WHERE ID_Cliente=6840104'
pd.read_sql(sql = text(query), con = engine.connect())

ID_Cliente  Edad     Grado_estudio Estado_civil  Tamaño_familia  \
0     6840104    62  Nivel intermedio   Divorciado               1   

  Categoria_de_renta Ocupacion  Años_empleado  Rendimiento_anual  Tiene_carro  \
0        Pensionista      Otro              0           135000.0            0   

                   Vivienda  
0  Casa/Departamento propio

In [ ]:
query = 'UPDATE clientes SET Rendimiento_anual = 300000 WHERE ID_Cliente=6840104'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('Se actualizó el registro', r_set.rowcount)

Se actualizó el registro 1


In [ ]:
query = 'SELECT * FROM clientes WHERE ID_Cliente=6840104'
pd.read_sql(sql = text(query), con = engine.connect())

ID_Cliente  Edad     Grado_estudio Estado_civil  Tamaño_familia  \
0     6840104    62  Nivel intermedio   Divorciado               1   

  Categoria_de_renta Ocupacion  Años_empleado  Rendimiento_anual  Tiene_carro  \
0        Pensionista      Otro              0           300000.0            0   

                   Vivienda  
0  Casa/Departamento propio

In [ ]:
query = 'SELECT * FROM clientes WHERE ID_Cliente=5008809'
pd.read_sql(sql = text(query), con = engine.connect())

ID_Cliente  Edad     Grado_estudio Estado_civil  Tamaño_familia  \
0     5008809    52  Nivel intermedio      Soltero               1   

  Categoria_de_renta Ocupacion  Años_empleado  Rendimiento_anual  Tiene_carro  \
0   Business Partner    Ventas              8           270000.0            0   

                   Vivienda  
0  Casa/Departamento propio

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('Se borró el registro', r_set.rowcount)

Se borró el registro 1


In [ ]:
query = 'SELECT * FROM clientes WHERE ID_Cliente=5008809'
pd.read_sql(sql = text(query), con = engine.connect())

Empty DataFrame
Columns: [ID_Cliente, Edad, Grado_estudio, Estado_civil, Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, Rendimiento_anual, Tiene_carro, Vivienda]
Index: []

In [ ]:
query = 'INSERT INTO clientes (ID_cliente, Edad, Grado_estudio, Estado_civil, Tamaño_familia, Categoria_de_renta, Ocupacion,Años_empleado, Rendimiento_anual, Tiene_carro, Vivienda) VALUES (6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", 2, 290000, 0, "Casa/Departamento propio")'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('Se insertó el registro', r_set.rowcount)


Se insertó el registro 1


In [ ]:
query = 'SELECT * FROM clientes WHERE ID_Cliente=6850985'
pd.read_sql(sql = text(query), con = engine.connect())

ID_Cliente  Edad Grado_estudio Estado_civil  Tamaño_familia  \
0     6850985    33     Doctorado      Soltero               1   

  Categoria_de_renta Ocupacion  Años_empleado  Rendimiento_anual  Tiene_carro  \
0           Empleado        TI              2           290000.0            0   

                   Vivienda  
0  Casa/Departamento propio

In [ ]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   
438462     6850985    33         Doctorado           Soltero               1   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   
438462           Empleado                  TI              2   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  
438462           290000.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]